www/protected/controllers/CheckoutController.php
<?php

class CheckoutController extends MiAController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('',),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('checkin','checkout','extend','admin','stats','repair','missing'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('overdue','enqueue'),
				'roles'=>array('admin', 'masteradmin',),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('',),
//				'users'=>array('admin'),
				'roles'=>array('masteradmin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Checkout('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Checkout']))
			$model->attributes=$_GET['Checkout'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}


	public function actionCheckout()
	{
    	$this->pageTitle = "Check-out";
		if(isset($_GET['Person']) && isset($_GET['Person']['id']))
		{
			$person = Person::model()->findByPk($_GET['Person']['id']);
			if(array_key_exists('notes', $_GET['Person']) && $person->notes != $_GET['Person']['notes'])
			{
    			$person->notes = $_GET['Person']['notes'];
    			$person->save();
                Yii::app()->user->setFlash('success', "Successfully updated notes");
			}

			if(isset($_GET['Book']) && isset($_GET['Book']['sn']) && $_GET['Book']['sn'])
			{
    			if(strlen($_GET['Book']['sn']) != Book::SN_LENGTH)
    			{
                    $book = new Book();
                    $message = "Barcode must be ".Book::SN_LENGTH." digits";
                    $book->addError('sn', $message);
					Yii::app()->user->setFlash('error', $message);
    			}
    			else
    			{
    				$books = Book::model()->findAll(array('condition'=>'sn='.$_GET['Book']['sn']));
    				if( ! count($books))
    				{

    					$message = "Book #".$_GET['Book']['sn']." does not exist!";
    					$book->addError('sn', $message);
    					Yii::app()->user->setFlash('error', $message);
    				}
    				else
    				{
    					$book = $books[0];

    					if($book->status_id == Book::STATUS_OUT)
    					{
    //     					add number, <title> by <name> due by <date>
    						$message = "Book '".$book->summary."' is already checked out by ".$book->currentcheckout->person->name." due by ".$book->currentcheckout->dueDate;
    						$book->addError('sn', $message);
    						Yii::app()->user->setFlash('error', $message);
    					}
    					else
    					{
    						$c = new Checkout();
    						$c->status_id = Checkout::STATUS_OUT;
    						$c->book_id = $book->id;
    						$c->person_id = $person->id;
    						$c->borrowDate = date("Y-m-d");
    						$c->dueDate = date('Y-m-d',strtotime('+'.$person->limitDays.' days',strtotime($c->borrowDate)));

    // move to checkout controller ??
    // add checkout count
    // add last checkout date

    						$c->save(false);

    						$book->status_id = Book::STATUS_OUT;
    						$book->save(false);
    // 						unset($book);

    						Yii::app()->user->setFlash('success', "Successfully checked out '".$book->summary."'");
    					}
    				}
    			}
			}
		}

		if( ! $person)
			$person = new Person();
		if( ! $book)
			$book = new Book();

		$this->render('checkout',array(
			'person'=>$person,
			'book'=>$book,
		));
	}

	public function actionCheckin()
	{
    	$this->pageTitle = "Check-in";
        if(isset($_GET['Person']))
        {
			$person = Person::model()->findByPk($_GET['Person']['id']);
			if($person->notes != $_GET['Person']['notes'])
			{
    			$person->notes = $_GET['Person']['notes'];
    			$person->save();
                Yii::app()->user->setFlash('success', "Successfully updated notes");
//                 print('updated note');
			}
        }


		if(isset($_GET['Book']) && isset($_GET['Book']['sn']) && $_GET['Book']['sn'])
		{

			if(strlen($_GET['Book']['sn']) != Book::SN_LENGTH)
			{
                $book = new Book();
    			$message = "Barcode must be ".Book::SN_LENGTH." digits";
                $book->addError('sn', $message);
				Yii::app()->user->setFlash('error', $message);
			}
			else
			{
    			$books = Book::model()->findAll(array('condition'=>'sn='.$_GET['Book']['sn']));
    			$cc = null;
    			if( ! count($books))
    			{
    				$book = new Book();
    				$message = "Book #".$_GET['Book']['sn']." does not exist!";
    				$book->addError('sn', $message);
    				Yii::app()->user->setFlash('error', $message);
    			}
    			else
    			{
    				$book = $books[0];

    				if($book->status_id == Book::STATUS_IN)
    				{
    					$message = "Book '".$book->summary."' is already checked in";
    					$book->addError('sn', $message);
    					Yii::app()->user->setFlash('error', $message);
    				}
    				elseif($book->status_id == Book::STATUS_REPAIR)
    				{
        				$message = "Book '".$book->summary."' is on repair";
    					$book->addError('sn', $message);
    					Yii::app()->user->setFlash('error', $message);
    				}
    				elseif($book->status_id == Book::STATUS_INCOMING)
    				{
        				$message = "Book '".$book->summary."' is still incoming";
    					$book->addError('sn', $message);
    					Yii::app()->user->setFlash('error', $message);
    				}
    				elseif($book->status_id == Book::STATUS_MISSING)
    				{
        				$message = "Book '".$book->summary."' is missing";
    					$book->addError('sn', $message);
    					Yii::app()->user->setFlash('error', $message);
    				}
    				else
    				{
    					if($book->currentcheckout){
    						$cc = $book->currentcheckout;
    						$cc->returnDate = date("Y-m-d");
    						$cc->status_id = Checkout::STATUS_IN;
    						$cc->save(false);
    					}
    					$book->status_id = Book::STATUS_IN;
    					$book->save(false);
    					Yii::app()->user->setFlash('success', "Successfully checked in '".$book->summary."'");
    // 					$book->sn = null;
    				}
    			}
			}
		}

		if( ! $book)
			$book = new Book();

		$this->render('checkin',array(
			'book'=>$book,
			'cc' => $cc,
		));
	}

    public function actionRepair($id)
    {
        $model = $this->loadBook($id);
        if($model->setRepair())
            Yii::app()->user->setFlash('success', "Marked '".$model->summary."' for repair");
        else
            Yii::app()->user->setFlash('important', "Error marking '".$model->summary."' for repair");
        $this->redirect(array('checkin'));
    }

    public function actionMissing($id)
    {
        $model = $this->loadBook($id);
        if($model->setMissing())
            Yii::app()->user->setFlash('success', "Marked '".$model->summary."' as missing");
        else
            Yii::app()->user->setFlash('important', "Error marking '".$model->summary."' as missing");
        $this->redirect(array('checkin'));
    }

	public function actionExtend($id)
	{
    	$this->pageTitle = "Extend";
		$model = $this->loadModel($id);
        $model->dueDate = date("Y-m-d", strtotime("+".$model->person->limitDays." days", strtotime($model->dueDate)));

		if(isset($_POST['Checkout']) && isset($_POST['Checkout']['dueDate']))
		{
			$model->attributes=$_POST['Checkout'];
			if($model->save(false, array('dueDate')))
			{
				Yii::app()->user->setFlash('success', "Extended successfully till ".$model->dueDate);
				$this->redirect(array('checkout','Person[id]'=>$model->person->id));
			}
			else
				Yii::app()->user->setFlash('success', "Error saving extension");
		}

		$this->render('extend',array(
			'model'=>$model,
		));
	}

	public function actionOverdue()
	{
    	$this->pageTitle = "Overdue";
		$model=new Checkout('search');
		$model->unsetAttributes();  // clear any default values
		$model->status_id = ">=".Checkout::STATUS_OUT; // != does not work
		$model->returnDate = "0000-00-00";

// print_r($model);

        if(Lookup::item('reminder', 'last_processed') != date("Y-m-d"))
        {
          $arrOverdue = $model->search(true)->getData();
          $arrRes = array();
          foreach($arrOverdue as $checkout)
          {
// print($checkout->id."<br/>");
            $r = $checkout->calculateReminderStatus_id();
            $arrRes[$r]++;
            $checkout->save(false);
          }
// print("<br/>");
// die('done');
          Lookup::saveItem('reminder', 'last_processed', date("Y-m-d"));
          $iEmailsToSend = 0;
          foreach($arrRes as $status => $count)
          {
	          if($status == Checkout::REMINDER_STATUS_READY1 ||
		          $status == Checkout::REMINDER_STATUS_READY2 ||
		          $status == Checkout::REMINDER_STATUS_READY3 ||
		          $status == Checkout::REMINDER_STATUS_READY1)
	          $iEmailsToSend += $count;
          }
          Yii::app()->user->setFlash('success', "Updated status of ".count($arrOverdue)." reminders. ".$iEmailsToSend." new emails to send");
        }
		if(isset($_GET['Checkout']))
			$model->attributes=$_GET['Checkout'];
        if( ! $model->status_id || $model->status_id == Checkout::STATUS_IN)
    		$model->status_id = ">".Checkout::STATUS_IN;

		$this->render('overdue',array(
			'model'=>$model,
		));
	}

www/protected/views/checkout/_list.php
<?php
$book = new Book();
$model = new Checkout();
if($book_id)
	$model->book_id = $book_id;
if($person_id)
	$model->person_id = $person_id;
if($returnDate)
	$model->returnDate = $returnDate;

$gridDataProvider = $model->searchList();

// $gridColumns
$gridColumns = array(

	'sn'=> array(
		'name' => 'sn',
		'value' => '$data->book->barcode',
		'header'=>$book->getAttributeLabel('sn'),
	),
	'title'=>	array(
		'name' => 'title',
		'value' => Yii::app()->user->roles == "masteradmin" || Yii::app()->user->roles == "admin" ?
		                'CHtml::link($data->book->title, array("book/update","id"=>$data->book->id)).$data->book->extraTitlesRich' :
		                'CHtml::link($data->book->title, array("book/view","id"=>$data->book->id)).$data->book->extraTitlesRich',
		'type' => 'raw',
		'header'=>$book->getAttributeLabel('title'),
	),
	'author' => array(
		'name' => 'author',
		'type' => 'raw',
		'value' => '$data->book->authorNamesLinks',
		'header'=>$book->getAttributeLabel('authorName'),
	),
	'languages'=> array(
		'name' => 'languages',
		'value' => '$data->book->languages',
		'header'=>$book->getAttributeLabel('languages'),
	),
	'ddc'=> array(
		'name' => 'ddc',
		'value' => '$data->book->ddc',
		'header'=>$book->getAttributeLabel('ddc'),
	),
	'number'=> array(
		'name' => 'number',
		'value' => '$data->book->number',
		'header'=>$book->getAttributeLabel('number'),
	),
	'person'=>	array(
		'name' => 'person',
		'value' => 'CHtml::link($data->person->summary, array("person/view","id"=>$data->person_id))',
		'type' => 'raw',
		'header'=> 'User',
	),
	'borrowDate' => array(
		'name' => 'borrowDate',
		'value' => '$data->borrowDate',
		'header'=>$book->getAttributeLabel('borrowDate'),
	),
	'dueDate' => array(
		'name' => 'dueDate',
		'value' => '$data->dueDate',
		'header'=>$book->getAttributeLabel('dueDate'),
	),
	'returnDate' => array(
		'name' => 'returnDate',
		'value' => '$data->returnDate',
		'header'=>$book->getAttributeLabel('returnDate'),
	),
	'status' => array(
		'name' => 'status',
		'type' => 'raw',
		'value' => '$data->statusBadge',
		'header'=>$book->getAttributeLabel('status'),
	),
	'extend' => array(
		'class'=> 'bootstrap.widgets.TbButtonColumn',
		'header' => 'Extend',
		'template' => '{extend}',
		'buttons' => array(
			'extend' => array(
				'visible' => '(Yii::app()->user->roles == "masteradmin" || Yii::app()->user->roles == "admin" || Yii::app()->user->roles == "staff") && $data->status_id == 2 || $data->status_id == 3 || $data->status_id == 4 ',
				'icon' => 'fa fa-arrows-h',
				'options'=>array('title'=>'Extend'),
				'url' => 'Yii::app()->createUrl("checkout/extend", array("id"=>$data->id))',
			),
		),
	),
);

if(is_array($arrHide))
	foreach($arrHide as $rem)
	{
		unset($gridColumns[$rem]);
	}

$this->widget(
    'bootstrap.widgets.TbGridView',
    array(
	    	'id'=>'checkout-grid',
    		'type' => Lookup::item('user_settings', 'ui_gridview_type'),
        'dataProvider' => $gridDataProvider,
				'template'=> Lookup::item('user_settings', 'ui_gridview_template'),
// 				'filter' => $model->search(),
        'columns' => $gridColumns,
				'pager' => array(
				  'class' => 'bootstrap.widgets.TbPager',
				  'displayFirstAndLast' => true,
				),
    )
);

if( $_GET['showall'] != 1)
    echo CHtml::link( "Show all", array_merge(array(Yii::app()->request->getPathInfo()), $_GET, array('showall'=>true)));
?>

www/protected/views/checkout/checkin.php
<h1>Check-in</h1>
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id'=>'checkin-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
  'type' => 'horizontal',
  'method' => 'get',
	'focus' => array($book,'sn'),
)); ?>
<fieldset>

<?php
if($cc)
{
?>
<h2>Last book checked in</h2>
<?php
  echo $form->textFieldRow(
    $book,
    'barcode',
    array(
	    'disabled' => 'disabled',
	    'id' => 'sndontsave',
	    'class' => 'span4',
    ),
    array('append'=>CHtml::link('<i class="fa fa-eye"></i>',array('book/view','id'=>$cc->book_id)))
  );
  $book->sn = null;
	echo $form->textFieldRow(
		$cc->book,
		'title',
    array(
	    'disabled' => 'disabled',
	    'class' => 'span4',
    ),
    array('append'=>CHtml::link('<i class="fa fa-eye"></i>',array('book/view','id'=>$cc->book_id)))
	);

	echo $form->textFieldRow(
		$cc->person,
		'summary',
    array(
	    'disabled' => 'disabled',
	    'class' => 'span4',
        'append'=>'m&sup2;'
    ),
    array('append'=>CHtml::link('<i class="fa fa-eye"></i>',array('person/view','id'=>$cc->person_id)))
	);

	echo $form->textFieldRow(
		$cc,
		'borrowDate',
	    array(
		    'disabled' => 'disabled',
		    'class' => 'span4',
	    )
	);

    echo $form->hiddenField(
        $cc->person,
        'id'
    );

/*
	echo $form->textAreaRow(
    $cc->person,
    'notes',
    array(
	    'rows' => 5,
	    'class' => 'span4',
// 	    'disabled' => 'disabled',
    )
  );
*/
?>
<?php
}
?>
<h2>Next book to check-in</h2>
<?php
// format barcode
if($book['sn'])
    $book['sn'] = $book->barcode;
echo $form->textFieldRow(
  $book,
  'sn',
  array(
    'class' => 'span4',
  )
);
?>
</fieldset>

<div class="form-actions">
<?php $this->widget(
  'bootstrap.widgets.TbButton',
  array(
    'buttonType' => 'submit',
    'type' => 'primary',
    'label' => "Check-in",
    'icon' => 'fa fa-check fa-fw',
  )
); ?>

<?php
if($book->id)
{
    $url = Yii::app()->createAbsoluteUrl('checkout/repair', array('id'=>$book->id));
$this->widget(
  'bootstrap.widgets.TbButton',
  array(
    'buttonType' => 'button',
    'type' => 'warning',
    'label' => "Repair",
    'icon' => 'fa fa-refresh fa-fw',
	'htmlOptions' => array(
		'onclick' => 'if($("#Book_sn").val() != "") bootbox.confirm("Mark book as \'repair\' ?",
										function(confirmed){
			                if(confirmed) {
			                   window.location = "'.$url.'";
			                }
					}); else window.location = "'.$url.'"',
	),
  )
);
?>

<?php
    $url = Yii::app()->createAbsoluteUrl('checkout/missing', array('id'=>$book->id));
$this->widget(
  'bootstrap.widgets.TbButton',
  array(
    'buttonType' => 'button',
    'type' => 'inverse',
    'label' => "Missing",
    'icon' => 'fa fa-question fa-fw',
	'htmlOptions' => array(
		'onclick' => 'if($("#Book_sn").val() != "") bootbox.confirm("Mark book as \'missing\' ?",
										function(confirmed){
			                if(confirmed) {
			                   window.location = "'.$url.'";
			                }
					}); else window.location = "'.$url.'"',
	),
  )
);
}
?>

</div>

<?php $this->endWidget(); ?>

www/protected/views/checkout/checkout.php
<h1>Check-out</h1>
<div id="badgelist" class="badgelist"><?php
if($person->id)
	echo $person->showBadges();
?></div>
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id'=>'checkout-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
  'type' => 'horizontal',
  'method' => 'get',
	'focus' => $person->canCheckout ? array($book,'sn') : array($person, 'name'),
)); ?>
<fieldset>
<?php echo $form->errorSummary($person); ?>
<?php // echo $form->errorSummary($book); ?>

<div class="control-group">
	<label class="control-label" for="<?php echo "person_id"; ?>">User Name</label>
	<div class="controls">
		<div class="input-append" onClick="$('#person_name').focus();">
<?php
	echo $form->hiddenField(
    $person,
    'id'
  );

	$this->widget('zii.widgets.jui.CJuiAutoComplete',array(
    'name'=>'Person[name]',
		'sourceUrl'=>$this->createUrl('person/ajaxItem'),
		'value'=>$person->summary,

    'options'=>array(
	    'minLength'=>'2',
	    'select'=>"js: function(event, ui) {
		 		$('#Person_id').val(ui.item['id']);
		 		$('#yw0').text('Select client');
		 		$('#Book_sn').parent().parent().hide();
		 		$('#Checkout').hide();
		 		$('#badgelist').hide();
		 		$('#yw0').prop('disabled', true);
		 		$('#checkout-form').submit();
			}",
    ),
    'htmlOptions'=>array(
        'class' => 'span4',
    )
	));
?>
		<span class="add-on"><i class="fa fa-ellipsis-h"></i></span>
<?php
if($person->id){
// 	echo "can borrow ".$person->borrowingQuota."book(s)";
	echo $person->quotaMessageRich;
}
?>
		</div>
	</div>
</div>

<?php
if($person->id)
{

	echo $form->textAreaRow(
	$person,
	'information',
    array(
	    'disabled' => 'disabled',
	    'class' => 'span4',
	    'rows' => '4',
    )
	);

	echo $form->textAreaRow(
    $person,
    'notes',
    array(
	    'rows' => '5',
	    'class' => 'span4',
// 	    'disabled' => 'disabled',
    )
  );

	if($person->overdue_id == Person::OVERDUE_DISABLED)
	{
		echo '<div class="control-group"><div class="controls">';
		echo Yii::app()->controller->widget(
	    'bootstrap.widgets.TbLabel',
	    array(
	        'type' => 'warning',
	        'label' => 'User has been disabled and cannot borrow any books'
	    ),
	    true
		);
		echo "</div></div>";
	}
	else
	{
		if($book->status_id == Book::STATUS_OUT)
			$book->sn = "";

		echo $form->textFieldRow(
	    $book,
	    'sn',
        array(
    	    'rows' => 5,
    	    'class' => 'span4',
        )
	  );
	}
}
?>

</fieldset>

<div class="form-actions">
<?php
if($person->canCheckout)
$this->widget(
    'bootstrap.widgets.TbButton',
    array(
        'buttonType' => 'submit',
        'type' => 'primary',
        'label' => $person->canCheckout ? "Check-out" : "Select user",
    )
);

if( ! $person->isnewrecord)
{
    $url = Yii::app()->createAbsoluteUrl('person/update', array('id'=>$person->id));
    print(" ");
    $this->widget(
        'bootstrap.widgets.TbButton',
        array(
            'type' => 'info',
            'label' => "Edit user",
        	'htmlOptions' => array(
				'onclick' => 'if($("#Book_sn").val() != "") bootbox.confirm("Edit user WITHOUT checking out book ?",
												function(confirmed){
					                if(confirmed) {
					                   window.location = "'.$url.'";
					                }
							}); else window.location = "'.$url.'"',
			),
        )
    );
?>

<?php
$url2 = Yii::app()->createAbsoluteUrl('checkout/checkout');
$this->widget(
'bootstrap.widgets.TbButton',
array(
    'buttonType' => 'button',
    'label' => 'Clear',
    'type' => 'inverse',
	'htmlOptions' => array(
		'onclick' => 'window.location = "'.$url2.'"',
	),
)
);
}
?>
</div>

<?php $this->endWidget(); ?>

<?php
if($person->id)
{
?>
<h2>Currently borrowed <small><?php echo CHtml::link('View entire history', array('/person/view', 'id'=>$person->id)); ?></h2>
<div id="checkout">
<?php
	$this->renderPartial('//checkout/_list', array('person_id'=>$person->id, 'returnDate'=>'0000-00-00', 'arrHide'=>array('person')));
}
?>
</div>

www/protected/views/checkout/extend.php
<h1>Extend</h1>
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id'=>'checkin-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
    'type' => 'horizontal',
	'focus' => array($model,'sn'),
)); ?>
<fieldset>
<?php echo $form->errorSummary($model) ?>
<?php
	echo $form->textFieldRow(
    $model->book,
    'summary',
    array(
	    'disabled' => 'disabled',
	    'class' => 'span4',
    )
  );

	echo $form->textFieldRow(
    $model->person,
    'summary',
    array(
	    'disabled' => 'disabled',
	    'class' => 'span4',
    )
  );

	echo $form->textFieldRow(
    $model,
    'borrowDate',
    array(
	    'disabled' => 'disabled',
	    'class' => 'span4',
    )
  );

  echo $form->datepickerRow(
    $model,
    'dueDate',
    array(
      'options' => unserialize(Lookup::item('user_settings', 'ui_calendar_format')),
      'htmlOptions' => array(
          'class' => 'span4',
      )
    ),
    array(
    	'append' => '<i class="icon-calendar" onClick="$(\'#Checkout_dueDate\').focus();"></i>',
        'hint'=>$model->extensionMessageRich,
    )
  );
?>

</fieldset>

<div class="form-actions">
<?php
$this->widget(
  'bootstrap.widgets.TbButton',
  array(
    'buttonType' => 'submit',
    'type' => 'primary',
    'label' => "Extend".($model->cannotExtend ? " anyway":""),
  )
);
?>
</div>

<?php $this->endWidget(); ?>

www/protected/views/checkout/overdue.php
<?php
$this->breadcrumbs=array(
	'List'=>array('admin'),
	'Overdue',
);
?>

<h1>Overdues</h1>


<?php
$countWithoutEmail = $model->overduesWithoutEmail();
if($countWithoutEmail)
{
  Yii::app()->controller->widget(
    'bootstrap.widgets.TbLabel',
    array(
  	  'type' => 'important',
  	  'label' => $countWithoutEmail > 1 ? $countWithoutEmail." users without email" : "1 user without email",
    )
  );
}

$countReadyToSend = $model->overduesReadyToSend();
$countText = $countReadyToSend > 1 ? $countReadyToSend." reminders" : $countReadyToSend." reminder";
if($countReadyToSend)
{
  Yii::app()->controller->widget(
    'bootstrap.widgets.TbLabel',
    array(
  	  'type' => 'info',
  	  'label' => "Ready to send ".$countText,
    )
  );

  echo "<br/><br/>";
  $this->widget(
    'bootstrap.widgets.TbButton',
    array(
      'label' => 'Send '.$countText,
      'htmlOptions' => array(
        'onclick' => 'bootbox.confirm("Do you really want to send '.$countText.' ?",
          function(confirmed){
            if(confirmed) {
              window.location = "'. Yii::app()->createAbsoluteUrl('checkout/enqueue').'";
            }
          })',
      ),
    )
  );
}


$book=new Book();

	$this->widget('bootstrap.widgets.TbGridView', array(
	'id'=>'Overdue-grid',
	'dataProvider'=>$model->search($_GET['showall']),
	'filter'=>$model,
	'type' => Lookup::item('user_settings', 'ui_gridview_type'),
  'rowCssClassExpression' => '( $row%2 ? $this->rowCssClass[1] : $this->rowCssClass[0] ) . ( $data->deletionDate ? " deleted" : null )',
	'pager' => array(
	  'class' => 'bootstrap.widgets.TbPager',
	  'displayFirstAndLast' => true,
	),

	'columns'=>array(
/*
		array(
			'name' => 'status_id',
			'type' => 'raw',
			'value' => '$data->statusBadge',
			'filter' => CHtml::listData(Lookup::lookupList('checkout_status'), 'id', 'title'),
		),
*/
		'book'=>array(
			'name' => 'search_book_sn',
			'type' => 'raw',
			'value' => '$data->book->summary',
		),
		'authors' => array(
			'header' => $book->getAttributeLabel('authorName'),
			'type' => 'raw',
			'value' => '$data->book->authorNamesLinks',
		),
/*
		'languages'=> array(
			'header'=>$book->getAttributeLabel('languages'),
			'value' => '$data->book->languages',
		),
*/
		'person'=>	array(
			'name'=> 'person_id',
			'type' => 'raw',
			'value' => 'CHtml::link($data->person->summary, array("person/view","id"=>$data->person_id))',
			'filter' => false,
		),
		'borrowDate',
		'dueDate',
// 		'returnDate',
		'reminderDate',
		'reminderCount',
		'reminderStatus' => array(
		  'name' => 'reminderStatus_id',
		  'filter' => CHtml::listData(Lookup::lookupList('reminder_status'), 'id', 'title'),
		  'type' => 'raw',
		  'value' => '$data->reminderStatusBadge',
		),
	),
));

if( $_GET['showall'] != 1)
    echo CHtml::link( "Show all", array_merge(array(Yii::app()->request->getPathInfo()), $_GET, array('showall'=>true)));
?>

www/protected/views/checkout/stats.php
<h1>Checkouts</h1>
<?php
$gridColumns = array(
	array('name'=>'year', 'header'=>'Year'),
	array('name'=>'checkouts', 'header'=>'Checkouts'),
);


if(is_array($stats) && count($stats))
{
	$dataProvider = new CArrayDataProvider($stats, array(
    'sort'=>array(
      'attributes'=>array('year','checkouts'),
      'defaultOrder'=>'year',
    ),
    'pagination'=>array(
			'pageSize'=>20,
    ),
  ));

	$this->widget(
    'bootstrap.widgets.TbGridView',
    array(
			'type' => Lookup::item('user_settings', 'ui_gridview_type'),
			'template'=>"{items}\n{pager}",
	    'dataProvider' => $dataProvider,
	    'template' => "{items}",
	    'columns' => $gridColumns,
'enableSorting'=>true,
    )
	);
}

/*
  	'id'=>'author_Book-grid',
    'dataProvider' => $gridDataProvider,
    'columns' => $gridColumns,
		'pager' => array(
		  'class' => 'bootstrap.widgets.TbPager',
		  'displayFirstAndLast' => true,
		),
*/

?>