www/protected/controllers/BookController.php
<?php

class BookController extends MiAController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('admin','search','view','listNew','listScores','excel'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('checkout','checkin','extend','ajaxPubPublisher','ajaxPubPlace','ajaxSeriesName', 'ajaxAgeGroup'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('create','update','delete','print','duplicate'),
				'roles'=>array('admin', 'masteradmin',),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('erase',),
//				'users'=>array('admin'),
				'roles'=>array('masteradmin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Book;
		$model->sn = $model->findNextSn();
		$model->status_id = Book::STATUS_INCOMING;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Book']))
		{
			$model->attributes=$_POST['Book'];

			if($model->save())
			{
				Yii::app()->user->setFlash('success', "Book successfully created!");
				$this->redirect(array('update','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	public function actionView($id)
	{
    	$this->pageTitle = "View";
		$model=$this->loadModel($id);
		$this->render('view',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
    	$this->pageTitle = "Update";
		$model=$this->loadModel($id);

/*
print_r($model);
die();
*/

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Book']))
		{
			$model->attributes=$_POST['Book'];
			if($model->save())
			{
				Yii::app()->user->setFlash('success', "Book successfully saved!");
// 				$this->redirect(array('admin'));
			}
		}

        if($model->form_duplicate == '1')
            $this->redirect(array('duplicate','id'=>$model->id));


		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Marks a particular model as deleted
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
    	$this->pageTitle = "Search";
		$model=new Book('search');
		$model->unsetAttributes();  // clear any default values
		if(Yii::app()->user->isGuest)
    		$model->deletionDate = "null";
		if(isset($_GET['Book']))
			$model->attributes=$_GET['Book'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	public function actionListNew()
	{
    	$this->pageTitle = "New";
		$model=new Book('search');
		$model->unsetAttributes();  // clear any default values
		$model->search_creationDate = (new DateTime("today -1 months"))->format('Y-m-d')." - ".(new DateTime("today"))->format('Y-m-d');
		if(Yii::app()->user->isGuest)
    		$model->deletionDate = "null";
		if(isset($_GET['Book']))
			$model->attributes=$_GET['Book'];

		$this->render('listNew',array(
			'model'=>$model,
		));
	}

  public function actionSearch()
  {
    $this->pageTitle = "Adv Search";
	$activeTab = $_GET['activeTab'];

	$model=new Book('search');
// 		$model->deletionDate = "null";
	$model->checkoutCount = null;
	$model->unsetAttributes();
    $bHideResults = true;

/*
if(count($_GET) || count($_POST))
{
    print_r($_GET);
    print("<hr>");
    print_r($_POST);
    die();
}
*/

    // Posted parameters
    if(isset($_GET['Book']) && isset($_GET['Book']['search_advanced_pre']))
    {
        $model->attributes=$_GET['Book'];
        $bHideResults = false;
    }
    // No post - use session variables
    else
    {
/*
print_r(Yii::app()->session);
die();
*/
      if(Yii::app()->session['search_advanced_pre'])
      {
        $model->search_advanced_pre = Yii::app()->session['search_advanced_pre'];
        // bHideResult is subject to $pre being set
      }
      if(Yii::app()->session['search_advanced_multiple'])
      {
        $model->search_advanced_multiple = Yii::app()->session['search_advanced_multiple'];
        $bHideResults = false;
      }
      if(Yii::app()->session['search_advanced_multiple_fields'])
      {
        $model->search_advanced_multiple_fields = Yii::app()->session['search_advanced_multiple_fields'];
        $bHideResults = false;
      }
      if(Yii::app()->session['search_advanced_custom_fields'])
      {
        $model->search_advanced_custom_fields = Yii::app()->session['search_advanced_custom_fields'];
        $bHideResults = false;
      }
    }
    // Make sure custom fields are ticked to defaults (less work for user)
    if( ! $model->search_advanced_custom_fields)
    {
      $model->search_advanced_custom_fields = $model->defaultSearchAttributes;
    }

    // pre-search filter submitted from corresponding cgridview
    if(isset($_REQUEST['Book']['search_advanced_pre_model'])
      && isset($_REQUEST['Book']['search_advanced_pre_model']['category'])
      && isset($_REQUEST['Book']['search_advanced_pre_model']['id'])
    )
    {
        if($_REQUEST['Book']['search_advanced_pre_model']['category'] != "" && $_REQUEST['Book']['search_advanced_pre_model']['id'] != "")
        {
            $preName = ucfirst($_REQUEST['Book']['search_advanced_pre_model']['category']);
            $pre =  new $preName;
            $model->search_advanced_pre_model = $pre::model()->findByPk($_REQUEST['Book']['search_advanced_pre_model']['id']);
        }
        else
        {
            $model->search_advanced_pre_model = null;
            Yii::app()->session['search_advanced_pre_model_category']   = null;
            Yii::app()->session['search_advanced_pre_model_id']         = null;
        }
    }
    elseif(Yii::app()->session['search_advanced_pre_model_category'] && Yii::app()->session['search_advanced_pre_model_id'])
    {
      $preName = ucfirst(Yii::app()->session['search_advanced_pre_model_category']);
      $pre =  new $preName;
      $model->search_advanced_pre_model = $pre::model()->findByPk(Yii::app()->session['search_advanced_pre_model_id']);
    }
    else
    {
      $model->search_advanced_pre_model = null;
    }

    // CGridView attributes come by $_GET
		if(isset($_GET['Book']))
		{
  		// Only CGridView search
          if($bHideResults)
          {
      			$model->attributes=$_GET['Book'];
          }
  		// Already top search form
  		else
  		{
    	  $modelGet = new Book('search');
  			$modelGet->attributes=$_GET['Book'];
  			foreach($modelGet->attributes as $attr => $val)
  			{
  			  if( ! $model->{$attr})
  			    $model->{$attr} = $val;
  			}
  		}
      $bHideResults = false;
		}

    if($activeTab)
    {
      switch($activeTab)
      {
        case "tab_pre":
          $model->search_advanced_multiple          = null;
          $model->search_advanced_multiple_fields   = null;
          // If no pre-search item has been selected, hide search results;
        break;
        case "tab_multiple":
          $model->search_advanced_pre               = null;
          if(isset($_GET['Book']['search_advanced_pre']))
            $_GET['Book']['search_advanced_pre']    = null;
        break;
        case "tab_custom":
          // Do nothing as this applies columsn for the other 2 tabs
          $activeTab = $_GET['Book']['search_advanced_pre'] != "" ? "tab_pre" : "tab_multiple";
        break;
      }
      // Remove remnant search_advanced_pre_model when using tab multiple
      // (also via tab_custom redirecting here - hence, outside the switch(){}
      if($activeTab == "tab_multiple")
      {
        $model->search_advanced_pre_model                               = null;
        if(isset($_REQUEST['Book']['search_advanced_pre_model']['category'] ))
          $_REQUEST['Book']['search_advanced_pre_model']['category']    = null;
        if(isset($_REQUEST['Book']['search_advanced_pre_model']['id'] ))
          $_REQUEST['Book']['search_advanced_pre_model']['id']          = null;
        Yii::app()->session['search_advanced_pre_model_category']       = null;
        Yii::app()->session['search_advanced_pre_model_id']             = null;
      }
    }

// die($model->search_advanced_pre_model);

    // Create pre-search results models
/*
    if($_GET['Book']['search_advanced_pre'] && !$_REQUEST['Book']['search_advanced_pre_model']['category'] && !$_REQUEST['Book']['search_advanced_pre_model']['id']
      || $_GET['Author'] || $_GET['Keyword'] || $_GET['Topicalterm']
    )
*/

www/protected/views/book/_form_create.php
<?php
/* @var $this meterController */
/* @var $model f */
/* @var $form CActiveForm */
?>

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id'=>'book-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
  'type' => 'horizontal',
  'focus' => array($model, 'sn'),
)); ?>

	<?php echo $form->errorSummary($model); ?>
    <fieldset>
	<div id="metadata_cover">
	</div>

<?php
	echo $form->textFieldRow(
    $model,
    'sn'
  );

	echo $form->textFieldRow(
    $model,
    'title'
  );
?>
    </fieldset>
    <div class="form-actions">
        <?php $this->widget(
            'bootstrap.widgets.TbButton',
            array(
                'buttonType' => 'submit',
                'type' => 'primary',
                'label' => $model->isNewRecord ? 'Create' : 'Save'
            )
        ); ?>
				<?php
				$url = Yii::app()->createAbsoluteUrl('book/admin');
        $this->widget(
            'bootstrap.widgets.TbButton',
            array(
            	'buttonType' => 'reset',
            	'label' => 'Cancel',
            	'htmlOptions' => array(
								'onclick' => 'bootbox.confirm("Discard changes ?",
																function(confirmed){
									                if(confirmed) {
									                   window.location = "'.$url.'";
									                }
																})',
							),
            )
        ); ?>
    </div>
<?php $this->endWidget(); ?>

www/protected/views/book/_list.php
<?php
$gridDataProvider = new CArrayDataProvider($books);
// $gridDataProvider->pagination = array('pageSize'=>Lookup::Item('user_settings','ui_gridview_size'));
$gridDataProvider->pagination = $_GET['showall'] == 1 ? false : array('pageSize'=>Lookup::Item('user_settings','ui_gridview_size'));
$gridDataProvider->sort = array('attributes' => array('sn','title','languages','ddc','number','status_id'));

$model = new Checkout();
$book = new Book();

if(! $author)
$author = new Author;

// $gridColumns
$gridColumns = array(
	'sn'=> array(
		'name' => 'sn',
		'value' => '$data->barcode',
		'header'=>$book->getAttributeLabel('sn'),
	),
	'title'=>	array(
		'name' => 'title',
		'value' => Yii::app()->user->roles == "masteradmin" || Yii::app()->user->roles == "admin" ?
		                'CHtml::link($data->title, array("book/update","id"=>$data->id)).$data->extraTitlesRich' :
		                'CHtml::link($data->title, array("book/view","id"=>$data->id)).$data->extraTitlesRich',
		'type' => 'raw',
		'header'=>$book->getAttributeLabel('title'),
	),
	'authorRole' => array(
    	'name' => 'authorRole',
		'header'=>$book->getAttributeLabel('authorRole'),
		'value' => '$data->authorRole('.$author->id.')'

	),
	'author' => array(
		'name' => 'author',
		'type' => 'raw',
		'value' => '$data->authorNamesLinks',
		'header'=>$book->getAttributeLabel('authorName'),
	),
	'languages'=> array(
		'name' => 'languages',
		'value' => '$data->languages',
		'header'=>$book->getAttributeLabel('languages'),
	),
    "ddc" => array(
    	'name' => 'ddc',
		'header'=>$book->getAttributeLabel('ddc'),
    ),
	"number" => array(
		'name' => 'number',
		'header'=>$book->getAttributeLabel('number'),
	),
	'status_id'=>array(
		'name' => 'status_id',
		'type'=>'raw',
		'value' => '$data->statusBadge',
		'header'=>$book->getAttributeLabel('status_id'),
	),
/*
	array(
		'name' => 'borrowDate',
		'value' => '$data->borrowDate',
		'header'=>$book->getAttributeLabel('borrowDate'),
	),
	array(
		'name' => 'dueDate',
		'value' => '$data->dueDate',
		'header'=>$book->getAttributeLabel('dueDate'),
	),
	array(
		'name' => 'returnDate',
		'value' => '$data->returnDate',
		'header'=>$book->getAttributeLabel('returnDate'),
	),
*/
);

if(is_array($arrHide))
	foreach($arrHide as $rem)
	{
		unset($gridColumns[$rem]);
	}

if($author->isNewRecord)
    unset($gridColumns['author_role']);


$this->widget(
    'bootstrap.widgets.TbGridView',
    array(
   		'type' => Lookup::item('user_settings', 'ui_gridview_type'),
        'dataProvider' => $gridDataProvider,
        'template' => "{items}",
// 				'filter' => $model->search(),
        'columns' => $gridColumns,
    	'pager' => array(
    	  'class' => 'bootstrap.widgets.TbPager',
    	  'displayFirstAndLast' => true,
    	),
        'template'=>"{summary}\n{items}\n{pager}",
    )
);

if( $_GET['showall'] != 1)
    echo CHtml::link( "Show all", array_merge(array(Yii::app()->request->getPathInfo()), $_GET, array('showall'=>true)));
?>

www/protected/views/book/_search_custom.php
<div class="well">Customise the search filters in the table below<br/>(This will not perform any search, but give you the option to filter on any combination of fields)</div>
<?php
$arrAttr = array();
foreach($model->advancedSearchCustomAttributes as $id => $attr)
  $arrAttr[$attr] = $model->getAttributeLabel($attr);

echo $form->checkBoxListRow(
  $model,
  'search_advanced_custom_fields',
  $arrAttr,
  array()
);

www/protected/views/book/_search_multiple.php
<div class="well">Search for the same text on multiple fields</div>
<?php
	echo $form->textFieldRow(
    $model,
    'search_advanced_multiple'
  );

$arrAttr = array();
foreach($model->advancedSearchMultipleAttributes as $id => $attr)
  $arrAttr[$id] = $model->getAttributeLabel($attr);

echo $form->checkBoxListRow(
  $model,
  'search_advanced_multiple_fields',
  $arrAttr
);

www/protected/views/book/admin.php
<?php
/* @var $this clientController */
/* @var $model client */

$this->breadcrumbs=array(
	'Book'=>array('admin'),
	'Search',
);

$this->menu=array(
	array('label'=>'Advanced Search', 'url'=>array('search')),
// 	array('label'=>'Create Book', 'url'=>array('create')),
	array('label'=>'Clear', 'url'=>array('admin')),
);
?>

<h1>Search book</h1>
<?php
if(Yii::app()->user->isGuest)
{
	print("To get your book, note both shelf number and specifier");
}

$dataProvider=$model->search();

// Determine the JavaScript to reset the filters.
// 'window.location.href' should be improved upon but is ok in most cases.
/*
$clearFilterData=CJavaScript::encode(
        array(
                'data' => array(
                        get_class($model) . '[]' => '',
                        $dataProvider->sort->sortVar => ' ',
                        $dataProvider->pagination->pageVar => 1
                ),
                'url' => new CJavaScriptExpression('window.location.href')
        ));
$jsClear=new CJavaScriptExpression("jQuery('#Book-grid').yiiGridView('update',$clearFilterData);");
$clearButton=CHtml::link(Yii::t('app','Clear'),'',array('onclick'=>$jsClear));
*/

$columns = array(
		"sn" => array(
			'name' => 'sn',
			'value' => '$data->barcode',
// 			'type' => 'raw',
// 			'filter' => CHtml::listData(Lookup::lookupList('activity_status'), 'id', 'title'),
		),
		"title" => array(
			'name' => 'title',
			'type' => 'raw',
			'value' => Yii::app()->user->roles == "masteradmin" || Yii::app()->user->roles == "admin" ?
			                'CHtml::link($data->title, array("book/update","id"=>$data->id)).$data->extraTitlesRich' :
			                'CHtml::link($data->title, array("book/view","id"=>$data->id)).$data->extraTitlesRich',
		),
		"authorNameCache" => array(
// 			'header'=>$author->getAttributeLabel('authorName'),
            'name'=>'authorNameCache',
			'type' => 'raw',
			'value' => '$data->authorNamesLinks',
// 			'value' => $model->search_author ? '$data->authorNamesLinks' : '$data->firstAuthorOnlyNameLink',
		),
		"languages" => array(
			'name' => 'languages',
// 			'type' => 'raw',
			'filter' => CHtml::listData(Lookup::lookupList('language'), 'title', 'title'),
		),
		"ddc" => array(
			'name' => 'ddc',
		),
		"number" => array(
			'name' => 'number',
		),
		"ageGroup" => array(
			'name' => 'ageGroup',
		),
		"status_id" => array(
			'name' => 'status_id',
			'value' => '$data->statusBadge',
			'type' => 'raw',
			'filter' => CHtml::listData(Lookup::lookupList('book_status'), 'id', 'title'),
		),
		'dueDate' => array(
    		'name' => 'dueDate',
            'filter' => false,
		),
		'borrowerName' => array(
    		'name' => 'borrowerName',
    		'value' => '$data->borrowerNameLink',
    		'type' => 'raw',
            'filter' => false,
		),
		"buttons" => array(
            'header'=>CHtml::link('Clear', 'admin', array('class'=>'clearbutton')),
/*
            'filterHtmlOptions'=>array(
              'onclick'=>$jsClear,
              'class'=>'clearFilter'
            ),
*/

			'htmlOptions' => array('nowrap'=>'nowrap'),
			'class'=>'bootstrap.widgets.TbButtonColumn',
			'template'=>'{view} {update}',

			'buttons' => array(
				'update' => array(
					'visible' => '(Yii::app()->user->roles == "masteradmin" || Yii::app()->user->roles == "admin")',
					'icon' => 'pencil',
				),
				'trash' => array(
					'visible' => '(Yii::app()->user->roles == "masteradmin" || Yii::app()->user->roles == "admin")',
					'icon' => 'trash',
				),
				'delete' => array(
					'visible' => '(Yii::app()->user->roles == "masteradmin" || Yii::app()->user->roles == "admin")',
					'icon' => 'remove',
				),
			),
		),
	);

if(Yii::app()->user->isGuest)
{
    unset($columns['sn']);
    unset($columns['borrowerName']);
}
if(Yii::app()->user->roles == "masteradmin" || Yii::app()->user->roles == "admin")
{
    unset($columns['dueDate']);
    unset($columns['borrowerName']);
}

$author = new Author();
$this->widget('bootstrap.widgets.TbGridView', array(
	'id'=>'Book-grid',
	'dataProvider'=>$dataProvider,
	'filter'=>$model,
	'type' => Lookup::item('user_settings', 'ui_gridview_type'),
    'rowCssClassExpression' => '( $row%2 ? $this->rowCssClass[1] : $this->rowCssClass[0] ) . ( $data->deletionDate ? " deleted" : null )',

	'selectableRows'=>1,
// 	'selectionChanged'=>'function(id){ location.href = "'.$this->createUrl('view').'?id="+$.fn.yiiGridView.getSelection(id);}',
	'pager' => array(
	  'class' => 'bootstrap.widgets.TbPager',
	  'displayFirstAndLast' => true,
	),
    'enableHistory' => 'true',
	'columns'=>$columns,
    'afterAjaxUpdate'=>'afterAjaxUpdate',
));

Yii::app()->clientScript->registerScriptFile(Yii::app()->getBaseUrl(true) . '/js/focuslastfield.js', CClientScript::POS_END);

if(Yii::app()->user->roles == "masteradmin" || Yii::app()->user->roles == "admin")
    $fieldname = "Book_sn";
else
    $fieldname = "Book_title";

Yii::app()->clientScript->registerScript(
    'focus_field',
    '$("#'.$fieldname.'").focus();',
    CClientScript::POS_READY
);

if( $_GET['showall'] != 1)
    echo CHtml::link( "Show all", array_merge(array(Yii::app()->request->getPathInfo()), $_GET, array('showall'=>true)));
?>

www/protected/views/book/listNew.php
<?php
/* @var $this clientController */
/* @var $model client */

$this->breadcrumbs=array(
	'Book'=>array('admin'),
	'Search',
);

$this->menu=array(
	array('label'=>'Advanced Search', 'url'=>array('search')),
	array('label'=>'Create Book', 'url'=>array('create')),
);
?>

<h1>New books</h1>
<?php // update this to dynamic dates ?? ?>
<?php
$month_start = new DateTime("today -1 months");
$month_end = new DateTime("today");

$week_start = new DateTime("today -1 weeks");
$week_end = new DateTime("today");

$today = new DateTime();

?>
<p>
<a href="javascript:updateDateRange('<?php echo $month_start->format('Y-m-d'); ?>','<?php echo $month_end->format('Y-m-d'); ?>');">Last month</a> -
<a href="javascript:updateDateRange('<?php echo $week_start->format('Y-m-d'); ?>','<?php echo $week_end->format('Y-m-d'); ?>');">Last Week</a> -
<a href="javascript:updateDateRange('<?php echo $today->format('Y-m-d'); ?>','<?php echo $today->format('Y-m-d'); ?>');">Today</a>
</p>
<?php
#http://www.daterangepicker.com/#options
$creationDateFilter = $this->widget('bootstrap.widgets.TbDateRangePicker', array(
						'model' => $model,
						'attribute' => 'search_creationDate',
	          'htmlOptions' => array(
	            'hint' => 'Click inside! An even a date range field!.',
							'value' => $model->search_creationDate,
							'size' => '15',
							'id' => 'Book_search_creationDate',
						),
	          'options' => array(
    	                    'format' => 'YYYY-MM-DD',
    	                    'locale' => array(
                                'firstDay' => 1,
    	                    ),
	          ),
						'callback' => 'js:function(start, end){ myUpdateGrid(start,end); }',
					), true);
?>
<script language="javascript">
function updateDateRange(strStartDate, strEndDate)
{
	// http://www.daterangepicker.com/#options
	$('#Book_search_creationDate').val(strStartDate+" - "+strEndDate);
	myUpdateGrid(strStartDate, strEndDate);
}
function myUpdateGrid(start, end)
{
	console.log('callback');

	// https://github.com/yiisoft/yii/blob/master/framework/zii/widgets/assets/gridview/jquery.yiigridview.js
	// http://queirozf.com/entries/yii-cgridview-javascript-functions-builtin-jquery-plugin
	href = $('#book-grid').yiiGridView('getUrl')
	if(href.indexOf("?") > 0)
	{
		var url = href.split('?');
		var params = $.deparam(url[1]);
	}
	else
	{
		var url = new Array(href);
		var params = new Object();
		params.Book = new Object();
	}
	params.Book.search_creationDate = $("#Book_search_creationDate").val();
	var updateUrl = $.param.querystring(url[0], params);

	console.log(url[1]);
	console.log(params);
	console.log(updateUrl);

// 	console.log($('#book-grid').yiiGridView);

	window.location = updateUrl;
// try to set url and use this:
// 	$('#book-grid').yiiGridView('update')
// $.fn.yiiGridView.update('book-grid')
}
</script>


<?php
$author = new Author();
$this->widget('bootstrap.widgets.TbGridView', array(
	'id'=>'book-grid',
// 	'ajaxUpdate'=>false,
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'type' => Lookup::item('user_settings', 'ui_gridview_type'),
    'rowCssClassExpression' => '( $row%2 ? $this->rowCssClass[1] : $this->rowCssClass[0] ) . ( $data->deletionDate ? " deleted" : null )',
    'enableHistory' => 'true',
	'selectableRows'=>1,
	'selectionChanged'=>'function(id){ location.href = "'.$this->createUrl('view').'?id="+$.fn.yiiGridView.getSelection(id);}',
	'pager' => array(
	  'class' => 'bootstrap.widgets.TbPager',
	  'displayFirstAndLast' => true,
	),

	'columns'=>array(
		array(
			'name' => 'creationDate',
			'filter' => $creationDateFilter,
		),
		array(
			'name' => 'status_id',
			'value' => '$data->statusBadge',
			'type' => 'raw',
			'filter' => CHtml::listData(Lookup::lookupList('book_status'), 'id', 'title'),
		),
		array(
			'name' => 'sn',
// 			'value' => '$data->statusBadge',
// 			'type' => 'raw',
// 			'filter' => CHtml::listData(Lookup::lookupList('activity_status'), 'id', 'title'),
		),
		array(
			'name' => 'title',
			'type' => 'raw',
			'value' => Yii::app()->user->roles == "masteradmin" || Yii::app()->user->roles == "admin" ?
			                'CHtml::link($data->title, array("book/update","id"=>$data->id))' :
			                'CHtml::link($data->title, array("book/view","id"=>$data->id))',
		),
		'author' => array(
// 			'header'=>$author->getAttributeLabel('authorName'),
      'name'=>'search_author',

			'type' => 'raw',
			'value' => '$data->authorNamesLinks',
		),
		array(
			'name' => 'languages',
// 			'type' => 'raw',
// 			'filter' => CHtml::listData(Lookup::lookupList('language'), 'id', 'title'),
			'filter' => CHtml::listData(Lookup::lookupList('language'), 'title', 'title'),

		),
		array(
			'name' => 'ddc',
		),
		array(
			'name' => 'number',
		),
		array(
			'name' => 'ageGroup',
		),

		array(
			'htmlOptions' => array('nowrap'=>'nowrap'),
			'class'=>'bootstrap.widgets.TbButtonColumn',
			'template'=>'{view} {update}',

			'buttons' => array(
				'update' => array(
					'visible' => '(Yii::app()->user->roles == "masteradmin" || Yii::app()->user->roles == "admin")',
					'icon' => 'pencil',
				),
			),
		),
	),
));

if( $_GET['showall'] != 1)
    echo CHtml::link( "Show all", array_merge(array(Yii::app()->request->getPathInfo()), $_GET, array('showall'=>true)));
?>