www/protected/controllers/AuthorController.php
<?php

class AuthorController extends MiAController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('admin','view',),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','ajaxItem','ajaxNotes'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('delete',),
				'roles'=>array('admin', 'masteradmin',),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('erase',),
//				'users'=>array('admin'),
				'roles'=>array('masteradmin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Author;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Author']))
		{
			$model->attributes=$_POST['Author'];

			if($model->save())
			{
				Yii::app()->user->setFlash('success', "Author successfully created!");
				$this->redirect(array('update','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	public function actionView($id)
	{
		$model=$this->loadModel($id);
		$this->render('view',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Author']))
		{
			$model->attributes=$_POST['Author'];
			if($model->save())
			{
				Yii::app()->user->setFlash('success', "Author successfully saved!");
// 				$this->redirect(array('admin'));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Marks a particular model as deleted
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Author('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Author']))
			$model->attributes=$_GET['Author'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Manages deleted models.
	 */
	public function actionAdminTrash()
	{
		$model=new Author('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Author']))
			$model->attributes=$_GET['Author'];

		$this->render('admin',array(
			'model'=>$model,
			'istrash'=>true,
		));
	}
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Activity the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Author::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Activity $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='Author-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	// data provider for EJuiAutoCompleteFkField for aurovilleName field
	public function actionAjaxItem($term)
	{
		$models=Author::model()->findAll(array(
			'condition'=>'name like :term OR nameFullerForm like :term',
			'params'=>array(':term'=>$term."%"),
			'order'=>'name',
		));

		$arrIds = array();
		if(count($models))
			foreach($models as $m)
				$arrIds[] = $m->id;


		if (!empty($models)) {
			$out = array();
			foreach ($models as $m) {
				$out[] = array(
					// expression to give the string for the autoComplete drop-down
					'label' => $m->summaryAutocomplete,
					'value' => $m->summaryAutocomplete,
					'id' => $m->id, // return value from autocomplete
				);
			}
			echo CJSON::encode($out);
			Yii::app()->end();
		}
	}

	// data provider for EJuiAutoCompleteFkField for Author > notes field
	public function actionAjaxNotes($term)
	{
		$models=Author::model()->findAll(array(
    		'select' => 'notes',
			'condition'=>'notes like :term',
			'params'=>array(':term'=>$term."%"),
			'order'=>'notes',
			'group' => 'notes'
		));

		$arrIds = array();
		if(count($models))
			foreach($models as $m)
				$arrIds[] = $m->id;


		if (!empty($models)) {
			$out = array();
			foreach ($models as $m) {
				$out[] = array(
					// expression to give the string for the autoComplete drop-down
					'label' => $m->notes,
					'value' => $m->notes,
					'id' => $m->id, // return value from autocomplete
				);
			}
			echo CJSON::encode($out);
			Yii::app()->end();
		}
    }
}

www/protected/controllers/BookController.php
<?php

class BookController extends MiAController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('admin','search','view','listNew','listScores','excel'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('checkout','checkin','extend','ajaxPubPublisher','ajaxPubPlace','ajaxSeriesName', 'ajaxAgeGroup'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('create','update','delete','print','duplicate'),
				'roles'=>array('admin', 'masteradmin',),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('erase',),
//				'users'=>array('admin'),
				'roles'=>array('masteradmin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Book;
		$model->sn = $model->findNextSn();
		$model->status_id = Book::STATUS_INCOMING;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Book']))
		{
			$model->attributes=$_POST['Book'];

			if($model->save())
			{
				Yii::app()->user->setFlash('success', "Book successfully created!");
				$this->redirect(array('update','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	public function actionView($id)
	{
    	$this->pageTitle = "View";
		$model=$this->loadModel($id);
		$this->render('view',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
    	$this->pageTitle = "Update";
		$model=$this->loadModel($id);

/*
print_r($model);
die();
*/

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Book']))
		{
			$model->attributes=$_POST['Book'];
			if($model->save())
			{
				Yii::app()->user->setFlash('success', "Book successfully saved!");
// 				$this->redirect(array('admin'));
			}
		}

        if($model->form_duplicate == '1')
            $this->redirect(array('duplicate','id'=>$model->id));


		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Marks a particular model as deleted
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
    	$this->pageTitle = "Search";
		$model=new Book('search');
		$model->unsetAttributes();  // clear any default values
		if(Yii::app()->user->isGuest)
    		$model->deletionDate = "null";
		if(isset($_GET['Book']))
			$model->attributes=$_GET['Book'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	public function actionListNew()
	{
    	$this->pageTitle = "New";
		$model=new Book('search');
		$model->unsetAttributes();  // clear any default values
		$model->search_creationDate = (new DateTime("today -1 months"))->format('Y-m-d')." - ".(new DateTime("today"))->format('Y-m-d');
		if(Yii::app()->user->isGuest)
    		$model->deletionDate = "null";
		if(isset($_GET['Book']))
			$model->attributes=$_GET['Book'];

		$this->render('listNew',array(
			'model'=>$model,
		));
	}

  public function actionSearch()
  {
    $this->pageTitle = "Adv Search";
	$activeTab = $_GET['activeTab'];

	$model=new Book('search');
// 		$model->deletionDate = "null";
	$model->checkoutCount = null;
	$model->unsetAttributes();
    $bHideResults = true;

/*
if(count($_GET) || count($_POST))
{
    print_r($_GET);
    print("<hr>");
    print_r($_POST);
    die();
}
*/

    // Posted parameters
    if(isset($_GET['Book']) && isset($_GET['Book']['search_advanced_pre']))
    {
        $model->attributes=$_GET['Book'];
        $bHideResults = false;
    }
    // No post - use session variables
    else
    {
/*
print_r(Yii::app()->session);
die();
*/
      if(Yii::app()->session['search_advanced_pre'])
      {
        $model->search_advanced_pre = Yii::app()->session['search_advanced_pre'];
        // bHideResult is subject to $pre being set
      }
      if(Yii::app()->session['search_advanced_multiple'])
      {
        $model->search_advanced_multiple = Yii::app()->session['search_advanced_multiple'];
        $bHideResults = false;
      }
      if(Yii::app()->session['search_advanced_multiple_fields'])
      {
        $model->search_advanced_multiple_fields = Yii::app()->session['search_advanced_multiple_fields'];
        $bHideResults = false;
      }
      if(Yii::app()->session['search_advanced_custom_fields'])
      {
        $model->search_advanced_custom_fields = Yii::app()->session['search_advanced_custom_fields'];
        $bHideResults = false;
      }
    }
    // Make sure custom fields are ticked to defaults (less work for user)
    if( ! $model->search_advanced_custom_fields)
    {
      $model->search_advanced_custom_fields = $model->defaultSearchAttributes;
    }

    // pre-search filter submitted from corresponding cgridview
    if(isset($_REQUEST['Book']['search_advanced_pre_model'])
      && isset($_REQUEST['Book']['search_advanced_pre_model']['category'])
      && isset($_REQUEST['Book']['search_advanced_pre_model']['id'])
    )
    {
        if($_REQUEST['Book']['search_advanced_pre_model']['category'] != "" && $_REQUEST['Book']['search_advanced_pre_model']['id'] != "")
        {
            $preName = ucfirst($_REQUEST['Book']['search_advanced_pre_model']['category']);
            $pre =  new $preName;
            $model->search_advanced_pre_model = $pre::model()->findByPk($_REQUEST['Book']['search_advanced_pre_model']['id']);
        }
        else
        {
            $model->search_advanced_pre_model = null;
            Yii::app()->session['search_advanced_pre_model_category']   = null;
            Yii::app()->session['search_advanced_pre_model_id']         = null;
        }
    }
    elseif(Yii::app()->session['search_advanced_pre_model_category'] && Yii::app()->session['search_advanced_pre_model_id'])
    {
      $preName = ucfirst(Yii::app()->session['search_advanced_pre_model_category']);
      $pre =  new $preName;
      $model->search_advanced_pre_model = $pre::model()->findByPk(Yii::app()->session['search_advanced_pre_model_id']);
    }
    else
    {
      $model->search_advanced_pre_model = null;
    }

    // CGridView attributes come by $_GET
		if(isset($_GET['Book']))
		{
  		// Only CGridView search
          if($bHideResults)
          {
      			$model->attributes=$_GET['Book'];
          }
  		// Already top search form
  		else
  		{
    	  $modelGet = new Book('search');
  			$modelGet->attributes=$_GET['Book'];
  			foreach($modelGet->attributes as $attr => $val)
  			{
  			  if( ! $model->{$attr})
  			    $model->{$attr} = $val;
  			}
  		}
      $bHideResults = false;
		}

    if($activeTab)
    {
      switch($activeTab)
      {
        case "tab_pre":
          $model->search_advanced_multiple          = null;
          $model->search_advanced_multiple_fields   = null;
          // If no pre-search item has been selected, hide search results;
        break;
        case "tab_multiple":
          $model->search_advanced_pre               = null;
          if(isset($_GET['Book']['search_advanced_pre']))
            $_GET['Book']['search_advanced_pre']    = null;
        break;
        case "tab_custom":
          // Do nothing as this applies columsn for the other 2 tabs
          $activeTab = $_GET['Book']['search_advanced_pre'] != "" ? "tab_pre" : "tab_multiple";
        break;
      }
      // Remove remnant search_advanced_pre_model when using tab multiple
      // (also via tab_custom redirecting here - hence, outside the switch(){}
      if($activeTab == "tab_multiple")
      {
        $model->search_advanced_pre_model                               = null;
        if(isset($_REQUEST['Book']['search_advanced_pre_model']['category'] ))
          $_REQUEST['Book']['search_advanced_pre_model']['category']    = null;
        if(isset($_REQUEST['Book']['search_advanced_pre_model']['id'] ))
          $_REQUEST['Book']['search_advanced_pre_model']['id']          = null;
        Yii::app()->session['search_advanced_pre_model_category']       = null;
        Yii::app()->session['search_advanced_pre_model_id']             = null;
      }
    }

// die($model->search_advanced_pre_model);

    // Create pre-search results models
/*
    if($_GET['Book']['search_advanced_pre'] && !$_REQUEST['Book']['search_advanced_pre_model']['category'] && !$_REQUEST['Book']['search_advanced_pre_model']['id']
      || $_GET['Author'] || $_GET['Keyword'] || $_GET['Topicalterm']
    )
*/

www/protected/views/author/_form.php
<?php
/* @var $this meterController */
/* @var $model f */
/* @var $form CActiveForm */
?>

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id'=>'author-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
  'type' => 'horizontal',
  'focus' => array($model, 'name'),
)); ?>

	<?php echo $form->errorSummary($model); ?>
    <fieldset>
	<div id="metadata_cover">
	</div>

<?php
	echo $form->textFieldRow(
    $model,
    'title'
  );

	echo $form->textFieldRow(
    $model,
    'name'
  );

	echo $form->textFieldRow(
    $model,
    'nameFullerForm'
  );

	echo $form->textFieldRow(
    $model,
    'lifetime'
  );

/*
	echo $form->textAreaRow(
    $model,
    'notes'
  );
*/
?>
<div class="control-group">
	<label class="control-label" for="<?php echo "notes"; ?>"><?php echo $model->getAttributeLabel('notes'); ?></label>
	<div class="controls">
		<div class="input-append" onClick="$('#author_name').focus();">
<?php
	$this->widget('zii.widgets.jui.CJuiAutoComplete',array(
    'name'=>'Author[notes]',
		'sourceUrl'=>$this->createUrl('author/ajaxNotes'),
		'value'=>$model->notes,

    'options'=>array(
	    'minLength'=>'3',
    ),
    'htmlOptions'=>array(
//         'class' => 'span4',
        'rows' => '5',
    )
	));

?>
		<span class="add-on"><i class="fa fa-ellipsis-h"></i></span>
		</div>
	</div>
</div>
    </fieldset>
    <div class="form-actions">
        <?php $this->widget(
            'bootstrap.widgets.TbButton',
            array(
                'buttonType' => 'submit',
                'type' => 'primary',
                'label' => $model->isNewRecord ? 'Create' : 'Save'
            )
        ); ?>
				<?php
				$url = Yii::app()->createAbsoluteUrl('author/admin');
        $this->widget(
            'bootstrap.widgets.TbButton',
            array(
            	'buttonType' => 'reset',
            	'label' => 'Cancel',
            	'htmlOptions' => array(
								'onclick' => 'bootbox.confirm("Discard changes ?",
																function(confirmed){
									                if(confirmed) {
									                   window.location = "'.$url.'";
									                }
																})',
							),
            )
        ); ?>
    </div>
<?php $this->endWidget(); ?>

www/protected/views/author/_gridedit.php
<?php
$model = new Author_Book();
$model->unsetAttributes();
$model->book_id = $book_id;

$gridDataProvider=$model->search();

$buttonPlus = CHtml::ajaxLink(
	CHtml::tag('i', array('class'=>'icon-plus'), ""),
	$this->createUrl('author_Book/ajaxCreate'),
	array(
		'type' => 'POST',
		'data' => array(
			'Author_Book[book_id]'    		  => $model->book_id,
			'Author_Book[author_id]'          => 'js:$("#author_id").val()',
			'Author_Book[role_id]'            => 'js:$("#author_role_id").val()',
		),
		'success' => 'function(html){ $.fn.yiiGridView.update("author_Book-grid"); }',
		'error' => 'function(html){ console.log(html.responseText); alert(html.responseText); }',
	),
	array(
		'data-original-title' => 'Assign to book',
		'data-toggle' => "tooltip",
	)
);

$buttonCreate = CHtml::link(
    CHtml::tag('i', array('class'=>'fa fa-list'), ""),
    Yii::app()->createUrl('author/create'),
    array(
        'target'=>'_blank',
        'data-original-title' => 'Create',
		'data-toggle' => "tooltip",
	),
	true
);

$gridColumns = array(
		array(
			'header' => $model->getAttributeLabel('author_id'),
			'name' => 'author_id',
			'value' => 'CHtml::link($data->author->summary, array("author/view", "id"=>$data->author_id), array("target"=>"_blank"), true)',
			'type' => 'raw',
			'footer' => CHtml::hiddenField('author_id' , 'value', array('id' => 'author_id')).$this->widget(
				'zii.widgets.jui.CJuiAutoComplete',
				array(
			    'name'=>'author_name',
				'sourceUrl'=>$this->createUrl('author/ajaxItem'),
                'options'=>array(
		            'minLength'=>'2',
                    'select'=>"js: function(event, ui) {
						 		$('#author_id').val(ui.item['id']);
							}",
			    ),
			    'htmlOptions'=>array(
						'placeholder' => "New ".$model->getAttributeLabel('author_id'),
						'class' => 'span-10'
					),
				),
				true),
		),
		array(
 			'class' => 'bootstrap.widgets.TbEditableColumn',
			'name' => 'role_id',
			'value' => '$data->roleBadge',
			'type'=>'raw',
			'filter' => CHtml::listData(Lookup::lookupList('author_role'), 'id', 'title'),
      'editable' => array(
	      'type' => 'select',
	      'source' => Lookup::items('author_role'),
        'url' => $this->createUrl('author_Book/ajaxUpdate'),
        'placement' => 'right',
        'inputclass' => 'span4',
        'attribute' => 'type_id',
				'onSave' => 'js:function(event, params) {	$("#author_Book-grid").yiiGridView("update"); }',
      ),
			'footer' => CHtml::dropDownList('role_id', null, Lookup::items('author_role'), array('empty' => '--Select--','class'=>'span1','id'=>'author_role_id')),
		),
		array(
			'name' => 'lifetime',
			'value' => '$data->author->lifetime',
		),
		array(
			'name' => 'notes',
			'value' => '$data->author->notes',
		),
		array(
			'class'=> 'bootstrap.widgets.TbButtonColumn',
// 			'template' => '{update} {view} {delete}',
			'template' => '{update} {delete}',
			'buttons' => array(
				'delete' => array(
					'visible' => '(Yii::app()->user->roles == "masteradmin" || Yii::app()->user->roles == "admin")',
					'icon' => 'remove',
					'options'=>array('title'=>'Unlink'),
					'url' => 'Yii::app()->createUrl("author_Book/delete", array("id"=>$data->id))',
				),
				'view' => array(
					'icon' => 'eye-open',
					'options' => array('title'=>'View'),
					'url' => 'Yii::app()->createUrl("author/view", array("id"=>$data->author_id))',
				),
				'update' => array(
					'options' => array('target'=>'_blank'),
					'url' => 'Yii::app()->createUrl("author/update", array("id"=>$data->author_id))',
				),

			),
			'footer' => $buttonPlus." ".$buttonCreate,
		),
);

$this->widget(
  'bootstrap.widgets.TbGridView',
  array(
    	'id'=>'author_Book-grid',
		'type' => Lookup::item('user_settings', 'ui_gridview_type'),
        'dataProvider' => $gridDataProvider,
		'template'=>"{items}\n{pager}",
        'columns' => $gridColumns,
		'pager' => array(
		  'class' => 'bootstrap.widgets.TbPager',
		  'displayFirstAndLast' => true,
		),
		'afterAjaxUpdate'=>"js:cgridReloadHandlerAuthorBook",
  )
);


Yii::app()->clientScript->registerScript('cgridReloadHandlerAuthorBook', '
function cgridReloadHandlerAuthorBook(id,data){
    jQuery("#author_name").autocomplete({"minLength":"2","select": function(event, ui) { $("#author_id").val(ui.item["id"]); },"source":"/author/ajaxItem"});
}');

www/protected/views/author/_list.php
<h2>Author</h2>

<?php
	$this->widget('bootstrap.widgets.TbGridView', array(
	'id'=>'Author-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'type' => Lookup::item('user_settings', 'ui_gridview_type'),

// 	'selectableRows'=>1,
// 	'selectionChanged'=>'function(id){ location.href = "'.$this->createUrl('view').'?id="+$.fn.yiiGridView.getSelection(id);}',
	'pager' => array(
	  'class' => 'bootstrap.widgets.TbPager',
	  'displayFirstAndLast' => true,
	),

	'columns'=>array(
		array(
			'name' => 'title',
		),
		array(
			'name' => 'name',
			'type' => 'raw',
			'value' => 'CHtml::link($data->name, array("author/view","id"=>$data->id))',
		),
		array(
			'name' => 'nameFullerForm',
		),
		array(
			'name' => 'lifetime',
		),
		array(
			'name' => 'notes',
		),

		array(
			'htmlOptions' => array('nowrap'=>'nowrap'),
			'class'=>'bootstrap.widgets.TbButtonColumn',
			'template'=>'{use}',

			'buttons' => array(
				'use' => array(
					'icon' => 'fa fa-check',
					'url' => 'Yii::app()->createUrl("book/search", array("Book[search_advanced_pre_model][category]"=>$data->tableName(),"Book[search_advanced_pre_model][id]"=>$data->id))',
					'label' => 'Use for pre-search',
				),
			),
		),
	),
));
?>

www/protected/views/author/admin.php
<?php
/* @var $this clientController */
/* @var $model client */

$this->breadcrumbs=array(
	'Author'=>array('admin'),
	'Search',
);

$this->menu=array(
	array('label'=>'Create Author', 'url'=>array('create')),
);
?>

<h1>Search Author</h1>

<?php
	$this->widget('bootstrap.widgets.TbGridView', array(
	'id'=>'Author-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'type' => Lookup::item('user_settings', 'ui_gridview_type'),
    'rowCssClassExpression' => '( $row%2 ? $this->rowCssClass[1] : $this->rowCssClass[0] ) . ( $data->deletionDate ? " deleted" : null )',
    'enableHistory' => 'true',

// 	'selectableRows'=>1,
// 	'selectionChanged'=>'function(id){ location.href = "'.$this->createUrl('view').'?id="+$.fn.yiiGridView.getSelection(id);}',
	'pager' => array(
	  'class' => 'bootstrap.widgets.TbPager',
	  'displayFirstAndLast' => true,
	),
	'columns'=>array(
		array(
			'name' => 'title',
		),
		array(
			'name' => 'name',
			'type' => 'raw',
			'value' => 'CHtml::link($data->name, array("author/view","id"=>$data->id))',
		),
		array(
			'name' => 'nameFullerForm',
		),
		array(
			'name' => 'lifetime',
		),
		array(
			'name' => 'notes',
		),

		array(
			'htmlOptions' => array('nowrap'=>'nowrap'),
			'class'=>'bootstrap.widgets.TbButtonColumn',
			'template'=>'{view} {update} {trash} {delete}',

			'buttons' => array(
				'update' => array(
					'visible' => '(Yii::app()->user->roles == "masteradmin" || Yii::app()->user->roles == "admin")',
					'icon' => 'pencil',
				),
				'trash' => array(
					'visible' => '(Yii::app()->user->roles == "masteradmin" || Yii::app()->user->roles == "admin")',
					'icon' => 'trash',
				),
				'delete' => array(
					'visible' => '(Yii::app()->user->roles == "masteradmin")',
					'icon' => 'delete',
				),
			),
		),
	),
));

 Yii::app()->clientScript->registerScript(
    'focus_name',
    '$("#Author_name").focus();',
   CClientScript::POS_READY
);

if( $_GET['showall'] != 1)
    echo CHtml::link( "Show all", array_merge(array(Yii::app()->request->getPathInfo()), $_GET, array('showall'=>true)));
?>

www/protected/views/author/create.php
<?php
/* @var $this PersonController */
/* @var $model Person */

$this->breadcrumbs=array(
	'Authors'=>array('admin'),
	'Create',
);

$this->menu=array(
// 	array('label'=>'Report', 'url'=>array('admin')),
);
?>

<h1>Create Author</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>